version: "3.8"
services:
  applicationone: 
    container_name: applicationone
    build:      
      context: .
      dockerfile: ./ApplicationOne/Dockerfile 
    ports:
      #  - 80
       - "8081:80"
    # networks:
    #   - net1
  applicationtwo:
    container_name: applicationtwo
    build:      
      context: .
      dockerfile: ./ApplicationTwo/Dockerfile 
    ports:
      - "8082:80"
  proxy:
    container_name: proxy
    build:      
      context: .
      dockerfile: ./proxy/Dockerfile 
    ports:
      - "8083:80"
    depends_on:
      - dapplicationoneb
      - applicationtwo
    # networks:
    #   - net1 
# configs:
#   my_config:
#     file: ./my_config.txt
#   my_other_config:
#     external: true